import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";
import { Inter } from "next/font/google";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Inter({subsets: ['latin']})

// const roboto = Roboto({
//   subsets: ['latin'],
//   weight: ['400', '500']
// })

// const poppins = localFont({
//   src: "./public/fonts/Poppins-SemiBold.ttf",
//   variable: "--font-poppins"
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  //Opengraph for sharing our pages on social media pages
  openGraph: {
    title: "...",
    description: "..."
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="synthawave">
      <GoogleAnalyticsScript />
      <body
        className={inter.className}
      >
        <AuthProvider>
      
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
